/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `wp_usermeta` VALUES
(1,1,"nickname","denis.silva"),
(2,1,"first_name",""),
(3,1,"last_name",""),
(4,1,"description",""),
(5,1,"rich_editing","true"),
(6,1,"syntax_highlighting","true"),
(7,1,"comment_shortcuts","false"),
(8,1,"admin_color","midnight"),
(9,1,"use_ssl","0"),
(10,1,"show_admin_bar_front","true"),
(11,1,"locale",""),
(12,1,"wp_capabilities","a:1:{s:13:\"administrator\";b:1;}"),
(13,1,"wp_user_level","10"),
(14,1,"dismissed_wp_pointers",""),
(15,1,"show_welcome_panel","1"),
(16,1,"session_tokens","a:1:{s:64:\"febc80bc3da81f607f8bffc2513f2be239525a27d223e5b279760bb887d78ed1\";a:4:{s:10:\"expiration\";i:1518273180;s:2:\"ip\";s:9:\"127.0.0.1\";s:2:\"ua\";s:114:\"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36\";s:5:\"login\";i:1518100380;}}"),
(17,1,"wp_dashboard_quick_press_last_post_id","3"),
(18,1,"community-events-location","a:1:{s:2:\"ip\";s:12:\"192.168.95.0\";}"),
(19,1,"wp_user-settings","mfold=o"),
(20,1,"wp_user-settings-time","1518100745"),
(21,1,"wp_yoast_notifications","a:4:{i:0;a:2:{s:7:\"message\";s:528:\"Yoast SEO and Advanced Custom Fields can work together a lot better by adding a helper plugin. Please install <a href=\"http://testewp.local/wp-admin/update.php?action=install-plugin&amp;plugin=acf-content-analysis-for-yoast-seo&amp;_wpnonce=46177a1526\">ACF Content Analysis for Yoast SEO</a> to make your life better. <a href=\"https://wordpress.org/plugins/acf-content-analysis-for-yoast-seo/\" aria-label=\"More information about ACF Content Analysis for Yoast SEO\" target=\"_blank\" rel=\"noopener noreferrer\">More information</a>.\";s:7:\"options\";a:8:{s:4:\"type\";s:7:\"warning\";s:2:\"id\";s:41:\"wpseo-suggested-plugin-yoast-acf-analysis\";s:5:\"nonce\";N;s:8:\"priority\";d:0.5;s:9:\"data_json\";a:0:{}s:13:\"dismissal_key\";N;s:12:\"capabilities\";a:1:{i:0;s:15:\"install_plugins\";}s:16:\"capability_check\";s:3:\"all\";}}i:1;a:2:{s:7:\"message\";s:163:\"Don\'t miss your crawl errors: <a href=\"http://testewp.local/wp-admin/admin.php?page=wpseo_search_console&tab=settings\">connect with Google Search Console here</a>.\";s:7:\"options\";a:8:{s:4:\"type\";s:7:\"warning\";s:2:\"id\";s:17:\"wpseo-dismiss-gsc\";s:5:\"nonce\";N;s:8:\"priority\";d:0.5;s:9:\"data_json\";a:0:{}s:13:\"dismissal_key\";N;s:12:\"capabilities\";s:20:\"wpseo_manage_options\";s:16:\"capability_check\";s:3:\"all\";}}i:2;a:2:{s:7:\"message\";s:267:\"You still have the default WordPress tagline, even an empty one is probably better. <a href=\"http://testewp.local/wp-admin/customize.php?url=http%3A%2F%2Ftestewp.local%2Fwp-admin%2Foptions-general.php%3Fsettings-updated%3Dtrue\">You can fix this in the customizer</a>.\";s:7:\"options\";a:8:{s:4:\"type\";s:5:\"error\";s:2:\"id\";s:28:\"wpseo-dismiss-tagline-notice\";s:5:\"nonce\";N;s:8:\"priority\";d:0.5;s:9:\"data_json\";a:0:{}s:13:\"dismissal_key\";N;s:12:\"capabilities\";s:20:\"wpseo_manage_options\";s:16:\"capability_check\";s:3:\"all\";}}i:3;a:2:{s:7:\"message\";s:217:\"<strong>Huge SEO Issue: You\'re blocking access to robots.</strong> You must <a href=\"http://testewp.local/wp-admin/options-reading.php\">go to your Reading Settings</a> and uncheck the box for Search Engine Visibility.\";s:7:\"options\";a:8:{s:4:\"type\";s:5:\"error\";s:2:\"id\";s:32:\"wpseo-dismiss-blog-public-notice\";s:5:\"nonce\";N;s:8:\"priority\";i:1;s:9:\"data_json\";a:0:{}s:13:\"dismissal_key\";N;s:12:\"capabilities\";s:20:\"wpseo_manage_options\";s:16:\"capability_check\";s:3:\"all\";}}}"),
(22,1,"_yoast_wpseo_profile_updated","1518117052"),
(23,1,"wpseo_title",""),
(24,1,"wpseo_metadesc",""),
(25,1,"wpseo_metakey",""),
(26,1,"wpseo_excludeauthorsitemap",""),
(27,1,"wpseo_content_analysis_disable",""),
(28,1,"wpseo_keyword_analysis_disable",""),
(29,1,"googleplus",""),
(30,1,"twitter",""),
(31,1,"facebook",""),
(32,2,"nickname","andre"),
(33,2,"first_name","andre"),
(34,2,"last_name","rafael"),
(35,2,"description",""),
(36,2,"rich_editing","true"),
(37,2,"syntax_highlighting","true"),
(38,2,"comment_shortcuts","false"),
(39,2,"admin_color","fresh"),
(40,2,"use_ssl","0"),
(41,2,"show_admin_bar_front","true"),
(42,2,"locale",""),
(43,2,"wp_capabilities","a:1:{s:6:\"author\";b:1;}"),
(44,2,"wp_user_level","2"),
(45,2,"_yoast_wpseo_profile_updated","1518117052"),
(46,2,"dismissed_wp_pointers","");
